apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:13.3
          env:
            - name: POSTGRES_USER
              value: ddueruem
            - name: POSTGRES_PASSWORD
              value: ddueruem
            - name: POSTGRES_DB
              value: ddueruem
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgresdata-pvc