apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend:latest
          envFrom:
            - secretRef:
                name: backend-env
          volumeMounts:
            - mountPath: /app
              name: backend-volume
            - mountPath: /api/media
              name: djangomedia
          command: ["sh", "entrypoint.sh"]
          ports:
            - containerPort: 8000
      volumes:
        - name: backend-volume
          hostPath:
            path: ./backend
        - name: djangomedia
          persistentVolumeClaim:
            claimName: djangomedia-pvc