apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: djangomedia-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  hostPath:
    path: "/mnt/data/djangomedia"