apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre-deployment
  labels:
    app: postgre
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
      - name: postgre
        image: postgres:13.3
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom: 
            secretKeyRef:
              name: postgres-secret
              key: postgre-user
        - name: POSTGRES_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: postgres-secret
              key: postgre-password
        volumeMounts:
          - name: postgre-persistent-storage
            mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgre-persistent-storage
        persistentVolumeClaim:
          claimName: postgre-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: postgre
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432